// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDibUqg4wLw3R-EfPFpK_BKBSYxDsz7wHA',
    appId: '1:108726598440:web:db1c5db845e0196594ae1d',
    messagingSenderId: '108726598440',
    projectId: 'chatify-25a03',
    authDomain: 'chatify-25a03.firebaseapp.com',
    storageBucket: 'chatify-25a03.firebasestorage.app',
    measurementId: 'G-21EFY6JHRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ZxSC-TRcM83dUo8_gWSMflElbjigsaI',
    appId: '1:108726598440:android:730e9b60041b15fb94ae1d',
    messagingSenderId: '108726598440',
    projectId: 'chatify-25a03',
    storageBucket: 'chatify-25a03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVO2UGhoPg5XbMsa4QnQz7WVOVHn0Hbo',
    appId: '1:108726598440:ios:935ef68f1775209794ae1d',
    messagingSenderId: '108726598440',
    projectId: 'chatify-25a03',
    storageBucket: 'chatify-25a03.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVO2UGhoPg5XbMsa4QnQz7WVOVHn0Hbo',
    appId: '1:108726598440:ios:935ef68f1775209794ae1d',
    messagingSenderId: '108726598440',
    projectId: 'chatify-25a03',
    storageBucket: 'chatify-25a03.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDibUqg4wLw3R-EfPFpK_BKBSYxDsz7wHA',
    appId: '1:108726598440:web:494379acb3b0997e94ae1d',
    messagingSenderId: '108726598440',
    projectId: 'chatify-25a03',
    authDomain: 'chatify-25a03.firebaseapp.com',
    storageBucket: 'chatify-25a03.firebasestorage.app',
    measurementId: 'G-NJWDF4C8YG',
  );
}
